# Generated by Django 4.2.1 on 2023-06-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartist',
            old_name='style_tattoo',
            new_name='tattoo_style',
        ),
    ]
