# Generated by Django 4.2.1 on 2023-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_studio_phone_studio'),
        ('user_artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='studio',
            field=models.ManyToManyField(blank=True, to='project.studio'),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='style_tattoo',
            field=models.ManyToManyField(blank=True, to='project.tattoostyle'),
        ),
    ]
