# Generated by Django 4.2.1 on 2023-05-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0002_alter_userartist_phone_alter_userartist_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='album',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='biography',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
