# Generated by Django 4.2.1 on 2023-06-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0002_rename_style_tattoo_userartist_tattoo_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userartist',
            name='studio',
        ),
        migrations.AddField(
            model_name='userartist',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userartist',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userartist',
            name='number_street',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userartist',
            name='post_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userartist',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userartist',
            name='street',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='userartist',
            name='studio_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
