# Generated by Django 4.2.1 on 2023-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0003_remove_userartist_studio_userartist_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartist',
            old_name='city',
            new_name='studio_city',
        ),
        migrations.RenameField(
            model_name='userartist',
            old_name='country',
            new_name='studio_country',
        ),
        migrations.RenameField(
            model_name='userartist',
            old_name='post_code',
            new_name='studio_number_street',
        ),
        migrations.RenameField(
            model_name='userartist',
            old_name='state',
            new_name='studio_state',
        ),
        migrations.RenameField(
            model_name='userartist',
            old_name='street',
            new_name='studio_street',
        ),
        migrations.RemoveField(
            model_name='userartist',
            name='number_street',
        ),
        migrations.AddField(
            model_name='userartist',
            name='studio_post_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
