# Generated by Django 4.2.1 on 2023-06-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0005_alter_userartist_album_alter_userartist_drawing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userartist',
            name='album',
        ),
        migrations.RemoveField(
            model_name='userartist',
            name='drawing',
        ),
    ]
