# Generated by Django 4.2.1 on 2023-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0006_remove_userartist_album_remove_userartist_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartist',
            name='album',
            field=models.ImageField(blank=True, null=True, upload_to='album/'),
        ),
        migrations.AddField(
            model_name='userartist',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='drawing/'),
        ),
    ]
