# Generated by Django 4.2.1 on 2023-06-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0008_remove_userartist_album_remove_userartist_drawing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartistalbum',
            old_name='album_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userartistdrawing',
            old_name='drawing_image',
            new_name='image',
        ),
    ]
