# Generated by Django 4.2.1 on 2023-06-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0009_rename_album_image_userartistalbum_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userartistalbum',
            old_name='id_user_artist',
            new_name='user_artist',
        ),
        migrations.RenameField(
            model_name='userartistdrawing',
            old_name='id_user_artist',
            new_name='user_artist',
        ),
    ]
