# Generated by Django 4.2.1 on 2023-05-29 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_studio', models.CharField(max_length=50)),
                ('phone_studio', models.CharField(max_length=10, unique=True)),
                ('number_street', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_style', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
