# Generated by Django 4.2.1 on 2023-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_studio_phone_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='name_studio',
            new_name='studio_name',
        ),
    ]
