# Generated by Django 4.2.1 on 2023-06-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_artist', '0003_remove_userartist_studio_userartist_city_and_more'),
        ('project', '0004_rename_name_style_tattoostyle_style_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
